
import React from 'react';
import { Link } from 'react-router-dom';
import { FEATURES, DEMO_REPORTS, PRICING_PLANS } from '../constants';
import { ArrowRightIcon, CheckCircleIcon } from '../components/IconComponents';
import { useAuth } from '../context/AuthContext';

const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-500 bg-green-100';
    if (score >= 70) return 'text-yellow-500 bg-yellow-100';
    return 'text-red-500 bg-red-100';
};

// Hero Section Component defined outside LandingPage
const HeroSection: React.FC = () => {
    const { currentUser } = useAuth();
    const ctaLink = currentUser ? '/dashboard' : '/signup';

    return (
        <section className="relative bg-gradient-to-br from-blue-50 via-white to-blue-50 py-20 md:py-32">
            <div className="container mx-auto px-6 text-center">
                <div className="max-w-3xl mx-auto">
                    <h1 className="text-4xl md:text-6xl font-extrabold text-gray-900 leading-tight">
                        Get Your Resume’s ATS Score in Seconds <span role="img" aria-label="rocket">🚀</span>
                    </h1>
                    <p className="mt-6 text-lg md:text-xl text-gray-600">
                        Upload your resume and instantly see how recruiters’ software views you. Our AI-powered analysis gives you the edge you need to land your dream job.
                    </p>
                    <Link
                        to={ctaLink}
                        className="mt-10 inline-flex items-center justify-center px-8 py-4 text-lg font-medium text-white bg-blue-600 rounded-lg shadow-lg hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 transition-all transform hover:scale-105"
                    >
                        Upload Resume
                        <ArrowRightIcon className="w-5 h-5 ml-2" />
                    </Link>
                </div>
            </div>
        </section>
    );
};


// Features Section Component
const FeaturesSection: React.FC = () => (
    <section id="features" className="py-20 bg-white">
        <div className="container mx-auto px-6">
            <div className="text-center mb-12">
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900">Why Choose Resume Genius Pro?</h2>
                <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">Everything you need to create a resume that stands out to both robots and humans.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                {FEATURES.map((feature, index) => (
                    <div key={index} className="bg-gray-50 p-8 rounded-xl border border-gray-200 hover:shadow-lg hover:border-blue-300 transition-all">
                        <div className="flex items-center justify-center h-12 w-12 rounded-full bg-blue-100 text-blue-600 mb-5">
                            <feature.icon className="w-6 h-6" />
                        </div>
                        <h3 className="text-xl font-semibold text-gray-900 mb-2">{feature.title}</h3>
                        <p className="text-gray-600">{feature.description}</p>
                    </div>
                ))}
            </div>
        </div>
    </section>
);

// Demo Section Component
const DemoSection: React.FC = () => (
    <section id="demo" className="py-20 bg-gray-50">
        <div className="container mx-auto px-6">
            <div className="text-center mb-12">
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900">See the Analysis in Action</h2>
                <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">Here are a few sample reports generated by our AI.</p>
            </div>
            <div className="space-y-6">
                {DEMO_REPORTS.map((report, index) => (
                    <div key={index} className="bg-white p-6 rounded-lg shadow-md border border-gray-200 grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
                        <div className="md:col-span-4">
                            <h3 className="font-semibold text-gray-800 break-all">{report.name}</h3>
                        </div>
                        <div className="md:col-span-2 text-center">
                            <span className={`px-4 py-2 text-lg font-bold rounded-full ${getScoreColor(report.score)}`}>
                                {report.score}
                            </span>
                        </div>
                        <div className="md:col-span-3">
                            <p className="text-sm font-medium text-gray-500 mb-2">Missing Skills:</p>
                            <div className="flex flex-wrap gap-2">
                                {report.missingSkills.map(skill => (
                                    <span key={skill} className="bg-red-100 text-red-700 text-xs font-medium px-2.5 py-1 rounded-full">{skill}</span>
                                ))}
                            </div>
                        </div>
                        <div className="md:col-span-3">
                            <p className="text-sm font-medium text-gray-500 mb-2">Suggestions:</p>
                            <p className="text-gray-700 text-sm">{report.suggestions}</p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    </section>
);

// Pricing Section Component
const PricingSection: React.FC = () => (
    <section id="pricing" className="py-20 bg-white">
        <div className="container mx-auto px-6">
            <div className="text-center mb-12">
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900">Simple, Transparent Pricing</h2>
                <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">Choose the plan that's right for your job search journey.</p>
            </div>
            <div className="flex flex-col lg:flex-row justify-center items-center gap-8">
                {PRICING_PLANS.map((plan) => (
                    <div key={plan.name} className={`w-full max-w-md p-8 rounded-2xl border ${plan.isFeatured ? 'border-blue-600 bg-gray-50 shadow-2xl' : 'border-gray-200 bg-white'}`}>
                        <h3 className="text-2xl font-semibold text-gray-900">{plan.name}</h3>
                        <p className="mt-4">
                            <span className="text-4xl font-extrabold text-gray-900">{plan.price}</span>
                            <span className="text-lg font-medium text-gray-500">{plan.frequency}</span>
                        </p>
                        <ul className="mt-8 space-y-4">
                            {plan.features.map(feature => (
                                <li key={feature} className="flex items-start">
                                    <CheckCircleIcon className="w-6 h-6 text-green-500 mr-3 flex-shrink-0 mt-0.5" />
                                    <span className="text-gray-600">{feature}</span>
                                </li>
                            ))}
                        </ul>
                        <button className={`w-full mt-10 py-3 px-6 rounded-lg font-semibold transition-all ${plan.isFeatured ? 'bg-blue-600 text-white hover:bg-blue-700' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}>
                            {plan.isFeatured ? 'Upgrade Now' : 'Get Started'}
                        </button>
                    </div>
                ))}
            </div>
        </div>
    </section>
);

// Contact Section Component
const ContactSection: React.FC = () => (
    <section id="contact" className="py-20 bg-gray-50">
        <div className="container mx-auto px-6">
            <div className="text-center mb-12">
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900">Get in Touch</h2>
                <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">Have questions? We'd love to hear from you.</p>
            </div>
            <div className="max-w-xl mx-auto bg-white p-8 rounded-lg shadow-md border border-gray-200">
                <form action="#" method="POST" className="space-y-6">
                    <div>
                        <label htmlFor="name" className="block text-sm font-medium text-gray-700">Name</label>
                        <input type="text" name="name" id="name" className="mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" />
                    </div>
                    <div>
                        <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
                        <input type="email" name="email" id="email" className="mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" />
                    </div>
                    <div>
                        <label htmlFor="message" className="block text-sm font-medium text-gray-700">Message</label>
                        <textarea id="message" name="message" rows={4} className="mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"></textarea>
                    </div>
                    <div>
                        <button type="submit" className="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                            Send Message
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </section>
);


const LandingPage: React.FC = () => {
    return (
        <>
            <HeroSection />
            <FeaturesSection />
            <DemoSection />
            <PricingSection />
            <ContactSection />
        </>
    );
};

export default LandingPage;
